name:                lambda
version:             0.1.0.0
author:              "Raffa Levy"
copyright:           "2020 Raffa Levy"
license:             "AllRightsReserved"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Senior Initative

dependencies:
- base >= 4.7 && < 5
- transformers
- lens

library:
  source-dirs: src

executables:
  lambda-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda

tests:
  lambda-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda
